apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: us-west1-docker.pkg.dev/microservices-445003/image-registry/payments-ms-prod
        name: payments-ms-prod
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: STRIPE_SUCCESS_URL
          value: "http://localhost:3000/payments/success"
        - name: STRIPE_CANCEL_URL
          value: "http://localhost:3000/payments/cancel"
        - name: STRIPE_SECRECT_KEY
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_secret_key
        - name: STRIPE_ENDPOINT_SECRECT
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_endpoint_secret
        - name: STRIPE_ENDPOINT_SECRECT_TESTING
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_endpoint_secrect_testing
        resources: {}
status: {}
